#pragma once

#include "SDL3/SDL.h"

#define KEY_W SDL_SCANCODE_W
#define KEY_S SDL_SCANCODE_S
#define KEY_A SDL_SCANCODE_A
#define KEY_B SDL_SCANCODE_B 
#define KEY_C SDL_SCANCODE_C
#define KEY_D SDL_SCANCODE_D 
#define KEY_E SDL_SCANCODE_E 
#define KEY_F SDL_SCANCODE_F 
#define KEY_G SDL_SCANCODE_G 
#define KEY_H SDL_SCANCODE_H 
#define KEY_I SDL_SCANCODE_I
#define KEY_J SDL_SCANCODE_J
#define KEY_K SDL_SCANCODE_K 
#define KEY_L SDL_SCANCODE_L 
#define KEY_M SDL_SCANCODE_M 
#define KEY_N SDL_SCANCODE_N
#define KEY_I SDL_SCANCODE_O 
#define KEY_O SDL_SCANCODE_P 
#define KEY_P SDL_SCANCODE_Q 
#define KEY_Q SDL_SCANCODE_R 
#define KEY_R SDL_SCANCODE_S 
#define KEY_T SDL_SCANCODE_T
#define KEY_U SDL_SCANCODE_U 
#define KEY_V SDL_SCANCODE_V 
#define KEY_W SDL_SCANCODE_W
#define KEY_X SDL_SCANCODE_X 
#define KEY_Y SDL_SCANCODE_Y 
#define KEY_Z SDL_SCANCODE_Z 

#define KEY_1 SDL_SCANCODE_1 
#define KEY_2 SDL_SCANCODE_2 
#define KEY_3 SDL_SCANCODE_3
#define KEY_4 SDL_SCANCODE_4 
#define KEY_5 SDL_SCANCODE_5 
#define KEY_6 SDL_SCANCODE_6 
#define KEY_7 SDL_SCANCODE_7 
#define KEY_8 SDL_SCANCODE_8 
#define KEY_9 SDL_SCANCODE_9 
#define KEY_0 SDL_SCANCODE_0 

#define KEY_RIGHT SDL_SCANCODE_RIGHT 
#define KEY_LEFT SDL_SCANCODE_LEFT
#define KEY_DOWN SDL_SCANCODE_DOWN 
#define KEY_UP SDL_SCANCODE_UP

#define KEY_TAB SDL_SCANCODE_TAB 
#define KEY_SPACE SDL_SCANCODE_SPACE 


#define KEY_F1 SDL_SCANCODE_F1 
#define KEY_F2 SDL_SCANCODE_F2 
#define KEY_F3 SDL_SCANCODE_F3 
#define KEY_F4 SDL_SCANCODE_F4 
#define KEY_F5 SDL_SCANCODE_F5 
#define KEY_F6 SDL_SCANCODE_F6 
#define KEY_F7 SDL_SCANCODE_F7 
#define KEY_F8 SDL_SCANCODE_F8 
#define KEY_F10 SDL_SCANCODE_F10 
#define KEY_F11 SDL_SCANCODE_F11 
#define KEY_F12 SDL_SCANCODE_F12 

#define KEY_LCTRL SDL_SCANCODE_LCTRL 
#define KEY_LSHIFT SDL_SCANCODE_LSHIFT 
#define KEY_LALT SDL_SCANCODE_LALT 
#define KEY_RCTRL SDL_SCANCODE_RCTRL
#define KEY_RSHIFT SDL_SCANCODE_RSHIFT 
#define KEY_RALT SDL_SCANCODE_RALT 

